version: "2.3"

services:

  ##
  # Debian Workspace
  ##
  shultu:
    container_name: shultu
    hostname: shultu
    # image: nobiki/shultu:latest
    image: shultu
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - shultu
    ports:
      - "80:80"
      - "443:443"
    env_file: ./.env
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - ${PWD}/bootstrap.sh:/bootstrap.sh
      - ${PWD}/dotfiles/:/tmp/dotfiles/:ro
      - /home/${LOGIN_ID}/:/home/${LOGIN_ID}/
    # runtime: nvidia
    tty: true
    init: true

networks:
  shultu:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
          gateway: 172.100.0.1
